version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
        - echo "Upgrading pip and wheel..."
        - pip install --upgrade pip wheel
        - echo "Pinning setuptools to a stable version (<= 68.0.0)..."
        - pip install "setuptools<=68.0.0"
        - pip show setuptools
        - pip list | grep setuptools
        - echo "Setting up virtual environment..."
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - echo "Ensuring setuptools inside venv is also downgraded..."
        - pip install "setuptools<=68.0.0"  # ✅ Fix applies inside venv
        - pip show setuptools
        - pip install -r requirements.txt
        - pip install zappa

  pre_build:
    commands:
      - python --version
      - pip show setuptools
      - python -c "import distutils" && echo "distutils is available!" || echo "distutils is missing!"
      - sleep 5

  build:
    commands:
      - echo Build lambda from flask and deploy using Zappa
      - zappa update dev  # Deploy/update Lambda
      #- zappa deploy dev  # Deploy/update Lambda

  post_build:
    commands:
      - echo "Deployment completed."

